---
#
# Ansible managed
#
repository:
  description: Install and configure sudo-pair on your system.
  homepage: https://robertdebock.nl/
  topics: sudopair, sudo, security, ansible, molecule, tox, playbook
